### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by whippingdot** [scratchxdiscord/scratchxdiscord.github.io#3]
I was looking through @Wjplatformer 's profile and found this.

![image](https://user-images.githubusercontent.com/64354499/175070673-cac0ddb6-dc0e-45f6-96f1-ee13e403089c.png)

Two things I circled. I ain't that good at web dev but one place needs padding and the link needs better styling. Also the background colors don't match and the black on the bottom looks horrible. I don't know why there is a circle around the scratch logo too.

**Comment by Wjplatformer** [comment]
@whippingdot , don't worry, I spent 2 hours on my life working on this. I did not dedicate full 12 hours on github on this. I will work on these, as to be really honest, the styling looks plain horrid. I might even create a navbar (lol)

**Comment by whippingdot** [comment]
Yes the styling does look horrid, I agree. Also 2 hours is a lot lol and so the design should be a little better. If you spent two hours of design that is kinda sad, but for 2 hours of total development, including HTML, this isn't that bad...

**Comment by Wjplatformer** [comment]
@whippingdot 2 hours for full development, and I have to convert markdown to HTML and the Badges were the real problem.

**Comment by devxan** [comment]
The html [scratchxdiscord.github.io](https://scratchxdiscord.github.io) is now a redirect to https://scratch.xan.lol, so all frontend previously created has been removed. To look at the site code as it used to be before this change, follow [this](https://github.com/scratchxdiscord/scratchxdiscord.github.io/tree/905dc86d06de95b1da240147c0a0c75ea6e3f8b8) link. 
In the future, this repository might switch back into being the official website.
